# Generated by Django 4.2.6 on 2023-10-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BenificiaryContact',
            new_name='BeneficiaryContact',
        ),
    ]
