# Generated by Django 4.2.6 on 2023-10-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_benificiarycontact_beneficiarycontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modified_date',
        ),
    ]
